version: 2.1

orbs:
  node-ecs: figure/node-ecs@3.0.0

workflows:
  terraform:
    jobs:
      - terraform_validate:
          context:
            - node

jobs:

  terraform_validate:
    executor: node-ecs/small
    steps:
      - checkout
      - run:
          name: "validate ecs-autoscaling-cpu"
          command: |
            cd ecs-autoscaling-cpu
            terraform init
            terraform validate
      - run:
          name: "validate ecs-service"
          command: |
            cd ecs-service
            terraform init
            terraform validate
      - run:
          name: "validate terraform-datadog-metric"
          command: |
            cd terraform-datadog-metric
            terraform init
            terraform validate
      - run:
          name: "validate terraform-datadog-metric-slo"
          command: |
            cd terraform-datadog-metric-slo
            terraform init
            terraform validate
      - run:
          name: "validate terraform-datadog-monitor-event-handler"
          command: |
            cd terraform-datadog-monitor-event-handler
            terraform init
            terraform validate
      - run:
          name: "validate terraform-datadog-monitor-express-endpoint"
          command: |
            cd terraform-datadog-monitor-express-endpoint
            terraform init
            terraform validate
      - run:
          name: "validate terraform-datadog-monitor-graphql-endpoint"
          command: |
            cd terraform-datadog-monitor-graphql-endpoint
            terraform init
            terraform validate
      - run:
          name: "validate terraform-datadog-sqs"
          command: |
            cd terraform-datadog-sqs
            terraform init
            terraform validate
      - node-ecs/slack_notify_fail_master:
          service_name: terraform-modules
