version: 2.1

orbs:
  node-ecs: figure/node-ecs@3.2.1

workflows:
  terraform:
    jobs:
      - terraform_validate:
          context:
            - node

jobs:

  terraform_validate:
    executor: node-ecs/small
    steps:
      - checkout
      - run:
          name: "validate aws-dynamodb-table"
          command: |
            cd aws-dynamodb-table
            terraform init
            terraform validate
      - run:
          name: "validate aws-sqs-queue"
          command: |
            cd aws-sqs-queue
            terraform init
            terraform validate
      - run:
          name: "validate datadog-monitor-express-endpoint"
          command: |
            cd datadog-monitor-express-endpoint
            terraform init
            terraform validate
      - run:
          name: "validate datadog-monitor-latency"
          command: |
            cd datadog-monitor-latency
            terraform init
            terraform validate
      - run:
          name: "validate datadog-monitor-metric"
          command: |
            cd datadog-monitor-metric
            terraform init
            terraform validate
      - run:
          name: "validate datadog-monitor-metric-slo"
          command: |
            cd datadog-monitor-metric-slo
            terraform init
            terraform validate
      - run:
          name: "validate datadog-sqs"
          command: |
            cd datadog-sqs
            terraform init
            terraform validate
      - run:
          name: "validate ecs-autoscaling-cpu"
          command: |
            cd ecs-autoscaling-cpu
            terraform init
            terraform validate
      - run:
          name: "validate ecs-service"
          command: |
            cd ecs-service
            terraform init
            terraform validate
      - node-ecs/slack_notify_fail_master:
          service_name: terraform-modules
